### ISSUE TITLE
[minidlna] /minidlna/cache/files.db on persistent volume

### ISSUE THREAD

**Issue by n00ris** [vladgh/docker_base_images#109] opened 2021-04-11 14:25 UTC
Hello,

at the moment, if you need to recreate your container, the files.db is lost and minidlna will do a full rescan of your media.

You may allow /minidlna/cache on a persistent volume, but add a possibility to rescan media.

My suggestion:

Since version 1.2.X there is a non-destructive update method, e.g. from changelog in [1]

```
1.2.0 - Released 17-May-2017
--------------------------------
[...]
- Add non-destructive update rescan support.
[...]
```` 

This option is `minidlnad -r`. (lower case `r`. The upper case `R` will do the destrcutive/full rescan.) [2]

So my suggestion is you add a startup script in the image that does a `minidlnad -r` if `/minidlna/cache/files.db` is present.

Maybe add a ENV variable to manage scans, e.g.:
SOFTSCAN_ON_STARTUP=true/false will add the "`minidlnad -r`" on every restart of the container.

Bonus / Not sure if needed:
FORCESCAN_ON_STARTUP=true/false will add "`minidlnad -R`" on every restart of the container. This will manage the full rescan similar for the case if `/minidlna/cache/files.db`  does not exists or after rebuild, but with cache volume.

[1] https://sourceforge.net/projects/minidlna/files/minidlna/1.3.0/
[2] https://stackoverflow.com/a/23187566

**Comment by n00ris** [comment] 2021-04-23 20:02
Hi  @accountForIssues . Thank you for your idea. Maybe you got me wrong: 
I am not speaking about restart / reboot.
I'm intereseted in a smooth update procedure.
I re-created the container to update the container itself to the latest version 
(high level procedure: pull latest image, delete container, start ne container with new image, keep volumes). 
Result: An update is similar to setup a very new container, you just keep data on your persistent volumes/bind mounts.

**Comment by accountForIssues** [comment] 2021-04-23 22:33
Okay, well using the docker-compose will let you do that.

I assume you were talking about the `docker run` command given in the README where there is a loss of data upon updating ? If so, that's what I was afraid as well and hence just went the compose route to write data to disk.

**Comment by vladgh** [comment] 2021-06-03 15:03
I am not quite sure I understand what the issue is, but I think this is intended behavior. The container does not mount any volumes, and no data is preserved between runs. Unless you specify runtime volumes that you want to keep (cache, settings, etc.). And in that case, @accountForIssues is perfectly right, you can `docker exec` the desired rescan commands into the running container.

**Comment by vladgh** [comment] 2021-10-01 14:59
> Okay, I don't see why that would hurt. I will work on it in the next few days.

And then Hurricane Ida hit my city, New Orleans!

But now I added 2 options to the environment:
- `FORCE_SCAN` will start with `-r`, which forces a rescan
- `FORCE_REBUILD` will start with `-R`, which forces a rebuild of the database

I hope that helps. If you want to test it, use the `vladgh/minidlna:sha-d3ba2bc` tag, but it should be merged and I will create a new release very soon.

**Comment by n00ris** [comment] 2021-10-01 17:48
> And then Hurricane Ida hit my city, New Orleans!

Oh wow, I hope you and your family are doing well.

> But now I added 2 options to the environment:
Thank you! It looks very much I was looking for. I really appreciate that very much.

I will check it out.

**Closed** 2021-12-26 15:33 UTC
Labels: enhancement
